import React from "react";
import type { Metadata } from "next";
import {
    Geist,
    Geist_Mono
} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// 西文无衬线字体（Geist）
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// 西文等宽字体（Geist Mono）
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 中文字体（霞鹜文楷 简洁版）
// LXGW WenKai Lite
const lxgwWenKaiLite = localFont({
    src: "../public/fonts/lxgw-wenkai-lite/LXGWWenKaiLite-Regular.ttf", // 字体文件路径
    variable: "--font-lxgwwenkai-lite", // 定义 CSS 变量
    display: "swap", // 字体加载策略：先显示系统字体，加载完成后替换
});

const lxgwWenKaiMonoLite = localFont({
    src: "../public/fonts/lxgw-wenkai-lite/LXGWWenKaiMonoLite-Regular.ttf", // 字体文件路径
    variable: "--font-lxgwwenkai-mono-lite", // 定义 CSS 变量
    display: "swap", // 字体加载策略：先显示系统字体，加载完成后替换
});

export const metadata: Metadata = {
  title: "Anxiu.Info Personal Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lxgwWenKaiLite.variable} ${lxgwWenKaiMonoLite.variable} antialiased`}
        style={{
            fontFamily: "var(--font-lxgwwenkai-lite), var(--font-geist-sans), sans-serif",
        }}
      >
        {children}
      </body>
    </html>
  );
}
