// This file is generated by Velite

export { default as techBlog } from './techBlog.json' with { type: 'json' }
export { default as bookBlog } from './bookBlog.json' with { type: 'json' }
export { default as lifeBlog } from './lifeBlog.json' with { type: 'json' }